# Site settings
title: Buckets Blog
email: hello@budgetwithbuckets.com
description: >
  A blog about budgeting with Buckets
baseurl: "https://blog.budgetwithbuckets.com"
url: "https://blog.budgetwithbuckets.com"

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jemoji