# Site settings
title: Buckets Blog
email: hello@budgetwithbuckets.com
description: >
  A blog about budgeting well.
baseurl: ""
url: "https://blog.budgetwithbuckets.com"

# Build settings
markdown: kramdown

gems:
  - jemoji