# Site settings
title: Buckets Blog
email: hello@bucketsisbetter.com
description: >
  A blog about budgeting well.
baseurl: ""
url: "https://blog.bucketsisbetter.com"

# Build settings
markdown: kramdown

gems:
  - jemoji